language: python
python:
 - "2.6"
 - "2.7"
install:
 - "pip install -e ."
 - "pip install pytz requests simplejson coverage django-coverage"
script: django-admin.py test --settings settings --traceback
services:
 - couchdb
