language: python
python:
 - "2.6"
 - "2.7"
install:
 - "pip install -e ."
 - "pip install pytz requests simplejson"
 - "pip install coverage coveralls"
script: "coverage run `which django-admin.py` test --settings settings --traceback couchforms"
after_success:
 - coveralls
services:
 - couchdb
